### ISSUE TITLE
Update model

### ISSUE THREAD

**Issue by zepouet** [Treeptik/cloudunit-maven-plugin#1]
The model object has changed. Need to update it.

```
[INFO] --- cloudunit-maven-plugin:1.0:deploy (default-cli) @ booking-mvc ---
[INFO] Connection successful
org.codehaus.jackson.map.exc.UnrecognizedPropertyException: Unrecognized field "cuInstanceName" (Class fr.treeptik.cloudunit.maven.plugin.model.Application), not marked as ignorable
 at [Source: java.io.StringReader@40d848f9; line: 1, column: 51] (through reference chain: fr.treeptik.cloudunit.maven.plugin.model.Application["cuInstanceName"])
    at org.codehaus.jackson.map.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:53)
    at org.codehaus.jackson.map.deser.StdDeserializationContext.unknownFieldException(StdDeserializationContext.java:267)
    at org.codehaus.jackson.map.deser.std.StdDeserializer.reportUnknownProperty(StdDeserializer.java:673)
    at org.codehaus.jackson.map.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:659)
```

**Comment by zepouet** [comment]
Missing too PortsToOpen
